config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  Rails.application.routes.draw do

  root to: 'artists#index'

  resources :songs

  resources :artists, only: [:index, :show] do
    resources :songs
  end

  resources :photos
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/artist.rb
class Artist < ApplicationRecord
  has_many :songs, dependent: :destroy

  validates :name, presence: true
end

app/models/song.rb
class Song < ApplicationRecord
  belongs_to :artist


  validates :title, presence: true
  validates :album, presence: true

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/artists_controller.rb
class ArtistsController < ApplicationController

  helper_method :sort_column, :sort_direction

    def index
      @artists = Artist.all
      @artists = Artist.order(sort_column + ' ' + sort_direction)

    end

    def sort_column
       Artist.column_names.include?(params[:sort]) ? params[:sort] : "name"
     end

     def sort_direction
       %w[asc desc].include?(params[:direction]) ? params[:direction] : "asc"
     end

  def show
    @artist = Artist.find(params[:id])
  end

end

app/controllers/songs_controller.rb
class SongsController < ApplicationController

before_action :set_song, only: [:show, :edit, :update]

  def current_artist
   return unless session[:artist_id]
      @current_artist ||= Artist.find(session[:artist_id])
    end

  def  index
    @songs = @current_artist.songs
  end

  def show

  end

  def new
    @song = @current_artist.songs.build
  end

  def create
  @song = @current_artist.songs.build(song_params)
  end

def edit
  if @song.save
    redirect_to @song, notice: "song successfully created"
  else
    render :new
  end
end

  def update
    if @song.update(song_params)
      redirect_to @song, notice: "song successfully updated"
    else
      render :edit
    end
  end

private
  def set_song
    @song = song.find(params[:id])
  end

  def song_params
    params.require(:song).permit(:title, :composer, :album)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/artists_helper.rb
module ArtistsHelper
end

app/helpers/songs_helper.rb
module SongsHelper
end

app/views/artists/index.html.erb
<h1>Artists</h1>

<% @artists.each do |artist| %>
  <p><%= link_to artist.name,
  artist_path(artist.id) %></p>
<% image_tag artist.image_url %>
<% end %>

app/views/artists/show.html.erb
<h1><%= "#{@artist.name}" " #{@artist.surname}" %></h1>


<p> Style: <%= @artist.style %></p>
<p> Country: <%= @artist.country %></p>
<p> Description: <%= @artist.description %></p>
<%= image_tag @artist.image_url %>

<h4>Song list</h4>

<% if @artist.songs.any? %>
  <ul>
    <% @artist.songs.each do |song| %>
      <li><%= song.title %></li>
    <% end %>
  </ul>
<% else %>
  <p>There are no songs attached to this artist.</p>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Codaisseurify</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/songs/_form.html.erb
<%= form_for @song do |f| %>
  <div class="form-group">
    <label>Title</label>
    <%= f.text_field :title, placeholder: "Song title", class: "form-control" %>
  </div>

  <div class="form-group">
    <label>Composer</label>
    <%= f.text_field :composer, placeholder: "Composer", class: "form-control" %>
  </div>

  <div class="form-group">
    <label>Album</label>
    <%= f.text_field :album, placeholder: "Album", class: "form-control" %>
  </div>

    <div class="actions">
    <%= f.submit "Save", class: "btn btn-primary" %>
  </div>
<% end %>

app/views/songs/edit.html.erb
<div class="panel panel-default">
  <div class="panel-heading">
    Edit title
  </div>

  <div class="panel-body">
    <%= render 'form' %>
  </div>
</div>

app/views/songs/index.html.erb
<h1>Songs</h1>

<% @songs.each do |song| %>
  <p><h3> Title: <%= song.title %></h3></p>
  <p> Composer: <%= song.composer %></p>
  <p> Album: <%= song.album %></p>
  <p> </p>
<% end %>

app/views/songs/new.html.erb
<div class="panel panel-default">
  <div class="panel-heading">
    Add a new title
  </div>

  <div class="panel-body">
    <%= render 'form' %>
  </div>
</div>

app/views/songs/show.html.erb
<div class="panel panel-primary">
  <div class="panel-heading"><%= @song.title %></div>

  <div class="panel-body">

    <p>Composer: <%= @song.composer %></p>
    <p>Album: <%= @song.album %></p>

      </div>

</div>

<%= link_to "Back", songs_path, class: "btn btn-default" %>